on:
  workflow_dispatch:
name: Publish All

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml

  # Publishing jobs - these run sequentially as before
  publish-muxado:
    name: Publish muxado
    uses: ./.github/workflows/release.yml
    needs: [ci]
    permissions:
      contents: write
    with:
      crate: muxado
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-ngrok:
    name: Publish ngrok
    uses: ./.github/workflows/release.yml
    needs: [publish-muxado]
    if: needs.publish-muxado.result == 'success' || needs.publish-muxado.result == 'skipped'
    permissions:
      contents: write
    with:
      crate: ngrok
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-cargo-doc-ngrok:
    name: Publish cargo-doc-ngrok
    uses: ./.github/workflows/release.yml
    needs: [publish-ngrok]
    if: needs.publish-ngrok.result == 'success' || needs.publish-ngrok.result == 'skipped'
    permissions:
      contents: write
    with:
      crate: cargo-doc-ngrok
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
